app/models/post.py
from sqlalchemy import Column, Integer, String, Text, ForeignKey
from sqlalchemy.orm import relationship
import bleach
from markdown import markdown

from .base import db, Base


class Post(Base):
    __tablename__ = 'post'

    id = Column(Integer, primary_key=True)
    title = Column(String(64), nullable=False)
    content = Column(Text)
    # user和post一对多关系
    user_id = Column(Integer, ForeignKey('user.id'), nullable=False)
    # 通过关系获取 user，这样获取默认返回的是一个列表，设置 uselist=false
    # 让它直接返回 user 对象
    user = relationship('User', backref='posts', uselist=False)
    # topic和post一对多关系
    topic_id = Column(Integer, ForeignKey('topic.id'), nullable=False)
    topic = relationship('Topic', backref='posts', uselist=False)

    content_html = Column(Text)

    def __repr__(self):
        return '<Post:{}>'.format(self.title)

    def to_dict(self):
        return {
            'id': self.id,
            'title': self.title,
            'content': self.content,
            'created_at': self.created_at,
            'user': self.user.to_dict(),
            'topic': self.topic.to_dict()
        }

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        # 需要转换的标签
        allowed_tags = [
            'a', 'abbr', 'acronym', 'b', 'blockquote', 'code', 'em', 'i', 'li',
            'ol', 'pre', 'strong', 'ul', 'h1', 'h2', 'h3', 'p', 'img'
        ]
        # 需要提取的标签属性，否则会被忽略掉
        attrs = {'*': ['class'], 'a': ['href', 'rel'], 'img': ['src', 'alt']}
        target.content_html = bleach.linkify(
            bleach.clean(
                markdown(value, output_format='html'),
                tags=allowed_tags,
                attributes=attrs,
                strip=True))


db.event.listen(Post.content, 'set', Post.on_changed_body)

app/views/auth.py
from flask import Blueprint, request, session, redirect, url_for, render_template
from flask_login import login_user, login_required, logout_user

from ..models import User
from ..forms import LoginForm


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        login_user(user)
        return redirect(url_for('main.index'))
    return render_template('login.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/views/main.py
from flask import Blueprint, request, render_template

from ..models import Post


main = Blueprint('main', __name__)


@main.route('/')
def index():
    # posts = Post.query.all()`
    page = request.args.get('page', 1, type=int)
    topic_id = request.args.get('topic_id', 0, type=int)
    if topic_id:
        pagination = Post.query.order_by(
            Post.created_at.desc()).filter_by(topic_id=topic_id).paginate(
                page, per_page=10, error_out=False)
    else:
        pagination = Post.query.order_by(Post.created_at.desc()).paginate(page, per_page=10, error_out=False)
    posts = pagination.items
    return render_template('index.html', posts=posts, pagination=pagination, topic_id=topic_id)


@main.route('/about')
def about_me():
    return render_template('about.html')

app/views/post.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from flask_login import login_required

from ..models import Post, Topic, Comment
from ..forms import PostForm, CommentForm


post = Blueprint('post', __name__, url_prefix='/post')


@post.route('/<int:id>', methods=['GET', 'POST'])
def post_view(id):
    form = CommentForm()
    if form.validate_on_submit():
        form.create_comment(id)
        return redirect(url_for('.post_view', id=id))
    post = Post.query.get(id)
    # 暂时返回10条评论
    comments = Comment.query.filter_by(post_id=id).order_by(Comment.created_at.desc()).limit(10)
    return render_template('post_view.html', post=post, form=form, comments=comments)


@post.route('/new', methods=['GET', 'POST'])
@login_required
def post_new():
    form = PostForm()
    if form.validate_on_submit():
        print('ok')
        form.create_post()
        return redirect(url_for('main.index'))
    return render_template('post_new.html', form=form)


@post.route('/search')
def post_search():
    kw = request.args.get('kw', None)
    page = request.args.get('page', 1, type=int)
    if kw:
        pagination = Post.query.filter(Post.title.like('%{}%'.format(kw))).order_by(Post.created_at.desc()).paginate(
            page, per_page=10, error_out=False)
        posts = pagination.items
        total = pagination.total
        return render_template('post_search.html', posts=posts, pagination=pagination, total=total)
    else:
        return redirect(url_for('main.index'))

app/templates/about.html
{% extends 'layout.html' %} 
{% block page_content %}
<div class="panel panel-default">
    <div class="panel-heading">个人信息</div>
    <div class="panel-body">
        Name: CC
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Github</h3>
    </div>
    <div class="panel-body">
        <a href="https://github.com/123woscc">https://github.com/123woscc</a>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Email</h3>
    </div>
    <div class="panel-body">
        <a href="#">123woscc@gmail.com</a>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}
{% block page_content %}
<div class="page-header">
    <h1>欢迎来到CC的博客
        <small>版本 1.0</small>
    </h1>
</div>
<div>
    {% for post in posts %}
    <div class="media">
        <div class="media-left">
            <a href="#">
                <img class="media-object" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PCEtLQpTb3VyY2UgVVJMOiBob2xkZXIuanMvNjR4NjQKQ3JlYXRlZCB3aXRoIEhvbGRlci5qcyAyLjYuMC4KTGVhcm4gbW9yZSBhdCBodHRwOi8vaG9sZGVyanMuY29tCihjKSAyMDEyLTIwMTUgSXZhbiBNYWxvcGluc2t5IC0gaHR0cDovL2ltc2t5LmNvCi0tPjxkZWZzPjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+PCFbQ0RBVEFbI2hvbGRlcl8xNjE3M2U0M2RjMiB0ZXh0IHsgZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQgfSBdXT48L3N0eWxlPjwvZGVmcz48ZyBpZD0iaG9sZGVyXzE2MTczZTQzZGMyIj48cmVjdCB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIGZpbGw9IiNFRUVFRUUiLz48Zz48dGV4dCB4PSIxMy4xNzk2ODc1IiB5PSIzNi41Ij42NHg2NDwvdGV4dD48L2c+PC9nPjwvc3ZnPg==" alt="...">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                <a href="{{url_for('post.post_view', id=post.id)}}">
                     {{post.title}}
                </a>
            </h4>
            {{post.content | truncate(10)}}
            {{post.created_at}}
        </div>
    </div>
    {% endfor %}
</div>
<div>
    <nav aria-label="...">
        <ul class="pager">
            <li class="{% if not pagination.has_prev %}disabled{% endif %}">
                <a href="{{url_for('.index', page=pagination.prev_num, topic_id=request.args.get('topic_id'))}}">Previous</a>
            </li>
            <li class="{% if not pagination.has_next %}disabled{% endif %}">
                <a href="{{url_for('.index', page=pagination.next_num, topic_id=request.args.get('topic_id'))}}">Next</a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

app/templates/layout.html
{% extends "bootstrap/base.html" %} 
{% block title %}{{ config.SITE_NAME }}{% endblock %} 
{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">{{ config.SITE_NAME }}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                         {% for t in topics %}
                            {% if t.id == request.args.get('topic_id') | int%}
                                {{t.name}}
                            {% endif %}
                         {% endfor %}
                         {% if not request.args.get('topic_id')%}
                            全部文章
                         {% endif %}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/">全部文章</a>
                        </li>
                        {% for t in topics %}
                        <li>
                            <a href="{{url_for('main.index', topic_id=t.id)}}">{{t.name}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                <li>
                    <a href="{{url_for('main.about_me')}}">About</a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" method="get" action="{{url_for('post.post_search')}}">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" id="kw" name='kw'>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        {{current_user.username}}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{url_for('post.post_new')}}">写文章</a>
                        </li>
                        <li>
                            <a href="{{url_for('admin.index')}}">后台管理</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="{{url_for('auth.logout')}}">Logout</a>
                        </li>
                    </ul>
                </li>

                {% else %}
                <li>
                    <a href="{{url_for('auth.login')}}">Login</a>
                </li>
                {% endif %}
                
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
{% endblock %} 
{% block content %}
<div class="container">
     {% block page_content %}
        <h1>Hello, Bootstrap</h1>
     {% endblock %}
</div>
{% endblock %}

app/templates/login.html
{% extends 'layout.html' %} 
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<h1 class="page_header">
    登录页面
</h1>
<div class="col-md-10">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/post_new.html
{% extends 'layout.html' %} 
{% block head %}
{{super()}}
{{ pagedown.include_pagedown() }}
{% endblock %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<h1 class="page_header">
    写文章
</h1>
<div class="row">
    <div class="col-md-6">
        <!-- {{ wtf.quick_form(form) }} -->
        <form method="POST">
             {{form.hidden_tag()}}
            {{ form.title(class="form-control") }}
            {{ form.topic(class="form-control") }}
            {{ form.content(only_input=True, rows=20, class="form-control") }} 
            {{ form.submit(class="btn btn-default")}}
        </form>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">预览</div>
            <div class="panel-body">
                 {{ form.content(only_preview=True, class="panel-body") }}
            </div>
        </div>
         
    </div>
</div>
{% endblock %}

app/templates/post_search.html
{% extends 'layout.html' %} {% block page_content %}
<div class="page-header">
    <h1>搜索结果
        <small>文章数目:{{total}}</small>
    </h1>
</div>
<div>
    {% for post in posts %}
    <div class="media">
        <div class="media-left">
            <a href="#">
                <img class="media-object" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PCEtLQpTb3VyY2UgVVJMOiBob2xkZXIuanMvNjR4NjQKQ3JlYXRlZCB3aXRoIEhvbGRlci5qcyAyLjYuMC4KTGVhcm4gbW9yZSBhdCBodHRwOi8vaG9sZGVyanMuY29tCihjKSAyMDEyLTIwMTUgSXZhbiBNYWxvcGluc2t5IC0gaHR0cDovL2ltc2t5LmNvCi0tPjxkZWZzPjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+PCFbQ0RBVEFbI2hvbGRlcl8xNjE3M2U0M2RjMiB0ZXh0IHsgZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQgfSBdXT48L3N0eWxlPjwvZGVmcz48ZyBpZD0iaG9sZGVyXzE2MTczZTQzZGMyIj48cmVjdCB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIGZpbGw9IiNFRUVFRUUiLz48Zz48dGV4dCB4PSIxMy4xNzk2ODc1IiB5PSIzNi41Ij42NHg2NDwvdGV4dD48L2c+PC9nPjwvc3ZnPg=="
                    alt="...">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                <a href="{{url_for('post.post_view', id=post.id)}}">
                    {{post.title}}
                </a>
            </h4>
            {{post.content | truncate(10)}} {{post.created_at}}
        </div>
    </div>
    {% endfor %}
</div>
<div>
    <nav aria-label="...">
        <ul class="pager">
            <li class="{% if not pagination.has_prev %}disabled{% endif %}">
                <a href="{{url_for('.post_search', page=pagination.prev_num, kw=request.args.get('kw'))}}">Previous</a>
            </li>
            <li class="{% if not pagination.has_next %}disabled{% endif %}">
                <a href="{{url_for('.post_search', page=pagination.next_num, kw=request.args.get('kw'))}}">Next</a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

app/templates/post_view.html
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<h1 class="page_header">
{{post.title}}
</h1>
<div>
    <!-- {{post.content}} -->
     {% if post.content_html %} 
        {{ post.content_html | safe }} 
    {% else %} 
        {{ post.content }} 
    {% endif %}
</div>
<br>
<h3 class="page_header">添加评论</h3>
<div>
    {{wtf.quick_form(form)}}
</div>
<br>
<h3>评论</h3>
<div>
    {% if comments %}
     {% for c in comments %}
    <div class="media">
        <div class="media-left">
            <a href="#">
                <img class="media-object" src="..." alt="...">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">{{c.name}}</h4>
            {{c.content}}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>暂无评论</p>
    {% endif %}
</div>
{% endblock %}